---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubectl-scaler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          serviceAccountName: kubectl-scaler
          containers:
            - name: kubectl-scaler
              image: bitnami/kubectl:1.25.11
              command: ["/bin/sh", "-c"]
              args:
                - kubectl scale deployment --replicas=0 --all
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-scaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-scaler
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubectl-scaler
subjects:
  - kind: ServiceAccount
    name: kubectl-scaler
    namespace: test
